// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvrSv7q5xpvuW9aKHWO8DfbNqi42foCIY',
    appId: '1:1056400319846:web:0ed16374cd4887671154a7',
    messagingSenderId: '1056400319846',
    projectId: 'flutter-crud-firebase-1a754',
    authDomain: 'flutter-crud-firebase-1a754.firebaseapp.com',
    storageBucket: 'flutter-crud-firebase-1a754.firebasestorage.app',
    measurementId: 'G-8KHYV3HQK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClNP7vBsDdHkeyjA0w6W4QfoJIVxEAkmU',
    appId: '1:1056400319846:android:3f804aafe62147c21154a7',
    messagingSenderId: '1056400319846',
    projectId: 'flutter-crud-firebase-1a754',
    storageBucket: 'flutter-crud-firebase-1a754.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2ocRC-uaGO9YGCeOu823b1mNOar8jRh0',
    appId: '1:1056400319846:ios:c75f2e7f7f96e23b1154a7',
    messagingSenderId: '1056400319846',
    projectId: 'flutter-crud-firebase-1a754',
    storageBucket: 'flutter-crud-firebase-1a754.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2ocRC-uaGO9YGCeOu823b1mNOar8jRh0',
    appId: '1:1056400319846:ios:c75f2e7f7f96e23b1154a7',
    messagingSenderId: '1056400319846',
    projectId: 'flutter-crud-firebase-1a754',
    storageBucket: 'flutter-crud-firebase-1a754.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvrSv7q5xpvuW9aKHWO8DfbNqi42foCIY',
    appId: '1:1056400319846:web:b1dda07fe7ea2da11154a7',
    messagingSenderId: '1056400319846',
    projectId: 'flutter-crud-firebase-1a754',
    authDomain: 'flutter-crud-firebase-1a754.firebaseapp.com',
    storageBucket: 'flutter-crud-firebase-1a754.firebasestorage.app',
    measurementId: 'G-3Q2Z476NW6',
  );
}
